org: fabricioladera
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  timeout: 30
  iam:
    role: arn:aws:iam::227165337884:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda

  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos
          method: post
          cors: true
          integration: lambda

  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/{tenant_id}/{alumno_id}
          method: get
          cors: true
          integration: lambda

  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos
          method: put
          cors: true
          integration: lambda

  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/{tenant_id}/{alumno_id}
          method: delete
          cors: true
          integration: lambda
